CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ANALYTICS.EXECUTIVE_KPI_SNAPSHOT AS
SELECT
    d.ON_TIME_DELIVERY_PCT,
    d.DELAY_RATE_PCT,
    d.AVG_DELIVERY_DELAY_DAYS,
    d.ORDER_COUNT,
    d.ORDER_ITEM_COUNT,
    d.TOTAL_SALES,
    d.TOTAL_PROFIT,
    d.PROFIT_MARGIN_PCT,
    l.SHIPMENT_COUNT,
    l.TOTAL_SHIPMENT_VALUE,
    l.TOTAL_FREIGHT_COST,
    l.TOTAL_INSURANCE_COST,
    l.LOGISTICS_COST_RATE_PCT,
    l.NULL_FREIGHT_PCT
FROM SUPPLYCHAINIQ_COCO.SEMANTIC.ENTERPRISE_DELIVERY_SCORECARD d
CROSS JOIN SUPPLYCHAINIQ_COCO.SEMANTIC.ENTERPRISE_LOGISTICS_SCORECARD l;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ANALYTICS.COUNTRY_PERFORMANCE_MATRIX AS
SELECT * FROM SUPPLYCHAINIQ_COCO.SEMANTIC.COUNTRY_CROSS_SOURCE_SCORECARD;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ANALYTICS.PRODUCT_CATEGORY_PERFORMANCE AS
SELECT
    CATEGORY_NAME,
    DEPARTMENT_NAME,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
    COUNT(*) AS ORDER_ITEM_COUNT,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER), 2) AS TOTAL_PROFIT,
    ROUND(100.0 * SUM(ORDER_PROFIT_PER_ORDER) / NULLIF(SUM(SALES), 0), 2) AS PROFIT_MARGIN_PCT,
    ROUND(100.0 * COUNT_IF(DELIVERY_STATUS IN ('Advance shipping','Shipping on time'))
        / NULLIF(COUNT_IF(DELIVERY_STATUS != 'Shipping canceled'), 0), 2) AS ON_TIME_DELIVERY_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT
GROUP BY CATEGORY_NAME, DEPARTMENT_NAME;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ANALYTICS.SHIPPING_MODE_ANALYSIS AS
SELECT
    'DataCo' AS SOURCE_SYSTEM,
    SHIPPING_MODE,
    COUNT(*) AS LINE_COUNT,
    ROUND(SUM(SALES), 2) AS TOTAL_VALUE,
    ROUND(100.0 * COUNT_IF(DELIVERY_STATUS IN ('Advance shipping','Shipping on time'))
        / NULLIF(COUNT_IF(DELIVERY_STATUS != 'Shipping canceled'), 0), 2) AS ON_TIME_DELIVERY_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT
GROUP BY SHIPPING_MODE
UNION ALL
SELECT
    'SCMS' AS SOURCE_SYSTEM,
    SHIPMENT_MODE AS SHIPPING_MODE,
    COUNT(*) AS LINE_COUNT,
    ROUND(SUM(LINE_ITEM_VALUE), 2) AS TOTAL_VALUE,
    NULL AS ON_TIME_DELIVERY_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.SCMS_SHIPMENT_FACT
GROUP BY SHIPMENT_MODE;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ANALYTICS.TOP_CUSTOMERS AS
SELECT
    f.CUSTOMER_ID,
    c.CUSTOMER_FNAME,
    c.CUSTOMER_LNAME,
    c.CUSTOMER_SEGMENT,
    c.CUSTOMER_COUNTRY,
    COUNT(DISTINCT f.ORDER_ID) AS ORDER_COUNT,
    COUNT(*) AS ORDER_ITEM_COUNT,
    ROUND(SUM(f.SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(f.ORDER_PROFIT_PER_ORDER), 2) AS TOTAL_PROFIT,
    ROUND(100.0 * COUNT_IF(f.DELIVERY_STATUS IN ('Advance shipping','Shipping on time'))
        / NULLIF(COUNT_IF(f.DELIVERY_STATUS != 'Shipping canceled'), 0), 2) AS ON_TIME_DELIVERY_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT f
JOIN SUPPLYCHAINIQ_COCO.CORE.CUSTOMER_DIM c ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY f.CUSTOMER_ID, c.CUSTOMER_FNAME, c.CUSTOMER_LNAME, c.CUSTOMER_SEGMENT, c.CUSTOMER_COUNTRY;
