CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.COUNTRY_DELIVERY_SCORECARD AS
SELECT
    ORDER_COUNTRY AS COUNTRY,
    COUNT_IF(DELIVERY_STATUS != 'Shipping canceled') AS NON_CANCELLED_ITEMS,
    COUNT_IF(DELIVERY_STATUS IN ('Advance shipping','Shipping on time')) AS ON_TIME_ITEMS,
    COUNT_IF(DELIVERY_STATUS = 'Late delivery') AS LATE_ITEMS,
    ROUND(100.0 * COUNT_IF(DELIVERY_STATUS IN ('Advance shipping','Shipping on time'))
        / NULLIF(COUNT_IF(DELIVERY_STATUS != 'Shipping canceled'), 0), 2) AS ON_TIME_DELIVERY_PCT,
    ROUND(100.0 * COUNT_IF(DELIVERY_STATUS = 'Late delivery')
        / NULLIF(COUNT_IF(DELIVERY_STATUS != 'Shipping canceled'), 0), 2) AS DELAY_RATE_PCT,
    ROUND(AVG(CASE WHEN DELIVERY_STATUS != 'Shipping canceled'
                    AND DAYS_FOR_SHIPPING_REAL > DAYS_FOR_SHIPMENT_SCHEDULED
              THEN DAYS_FOR_SHIPPING_REAL - DAYS_FOR_SHIPMENT_SCHEDULED END), 2) AS AVG_DELIVERY_DELAY_DAYS,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
    COUNT(*) AS ORDER_ITEM_COUNT,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER), 2) AS TOTAL_PROFIT
FROM SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT
GROUP BY ORDER_COUNTRY;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.COUNTRY_LOGISTICS_SCORECARD AS
SELECT
    COUNTRY,
    COUNT(*) AS SHIPMENT_COUNT,
    ROUND(SUM(LINE_ITEM_VALUE), 2) AS SHIPMENT_VALUE_USD,
    ROUND(SUM(FREIGHT_COST_USD), 2) AS FREIGHT_COST_USD,
    ROUND(SUM(LINE_ITEM_INSURANCE_USD), 2) AS INSURANCE_COST_USD,
    ROUND(100.0 * SUM(FREIGHT_COST_USD) / NULLIF(SUM(LINE_ITEM_VALUE), 0), 6) AS LOGISTICS_COST_RATE_PCT,
    ROUND(AVG(WEIGHT_KILOGRAMS), 2) AS AVG_WEIGHT_KG
FROM SUPPLYCHAINIQ_COCO.CORE.SCMS_SHIPMENT_FACT
GROUP BY COUNTRY;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.COUNTRY_CROSS_SOURCE_SCORECARD AS
SELECT
    COALESCE(d.COUNTRY, l.COUNTRY) AS COUNTRY,
    d.ON_TIME_DELIVERY_PCT,
    d.DELAY_RATE_PCT,
    d.AVG_DELIVERY_DELAY_DAYS,
    d.ORDER_ITEM_COUNT,
    d.TOTAL_SALES,
    d.TOTAL_PROFIT,
    l.SHIPMENT_COUNT,
    l.SHIPMENT_VALUE_USD,
    l.FREIGHT_COST_USD,
    l.INSURANCE_COST_USD,
    l.LOGISTICS_COST_RATE_PCT,
    CASE WHEN d.COUNTRY IS NOT NULL AND l.COUNTRY IS NOT NULL THEN 'BOTH'
         WHEN d.COUNTRY IS NOT NULL THEN 'DATACO_ONLY'
         ELSE 'SCMS_ONLY' END AS SOURCE_COVERAGE
FROM SUPPLYCHAINIQ_COCO.SEMANTIC.COUNTRY_DELIVERY_SCORECARD d
FULL OUTER JOIN SUPPLYCHAINIQ_COCO.SEMANTIC.COUNTRY_LOGISTICS_SCORECARD l
    ON d.COUNTRY = l.COUNTRY;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.COUNTRY_RISK_ASSESSMENT AS
WITH delivery_stats AS (
    SELECT * FROM SUPPLYCHAINIQ_COCO.SEMANTIC.COUNTRY_DELIVERY_SCORECARD
),
logistics_stats AS (
    SELECT * FROM SUPPLYCHAINIQ_COCO.SEMANTIC.COUNTRY_LOGISTICS_SCORECARD
),
combined AS (
    SELECT
        COALESCE(d.COUNTRY, l.COUNTRY) AS COUNTRY,
        d.ON_TIME_DELIVERY_PCT,
        d.DELAY_RATE_PCT,
        d.AVG_DELIVERY_DELAY_DAYS,
        l.SHIPMENT_COUNT,
        l.SHIPMENT_VALUE_USD,
        l.FREIGHT_COST_USD,
        l.LOGISTICS_COST_RATE_PCT
    FROM delivery_stats d
    FULL OUTER JOIN logistics_stats l ON d.COUNTRY = l.COUNTRY
),
medians AS (
    SELECT
        MEDIAN(DELAY_RATE_PCT)         AS MEDIAN_DELAY_RATE,
        MEDIAN(LOGISTICS_COST_RATE_PCT) AS MEDIAN_LOGISTICS_RATE,
        MEDIAN(FREIGHT_COST_USD)        AS MEDIAN_FREIGHT_COST
    FROM combined
)
SELECT
    c.COUNTRY,
    c.ON_TIME_DELIVERY_PCT,
    c.DELAY_RATE_PCT,
    c.AVG_DELIVERY_DELAY_DAYS,
    c.SHIPMENT_COUNT,
    c.SHIPMENT_VALUE_USD,
    c.FREIGHT_COST_USD,
    c.LOGISTICS_COST_RATE_PCT,
    m.MEDIAN_DELAY_RATE AS MEDIAN_DELAY_RATE_PCT,
    m.MEDIAN_LOGISTICS_RATE AS MEDIAN_LOGISTICS_COST_RATE_PCT,
    m.MEDIAN_FREIGHT_COST AS MEDIAN_FREIGHT_COST_USD,
    IFF(c.DELAY_RATE_PCT > m.MEDIAN_DELAY_RATE, TRUE, FALSE) AS HIGH_DELAY_FLAG,
    IFF(c.LOGISTICS_COST_RATE_PCT > m.MEDIAN_LOGISTICS_RATE, TRUE, FALSE) AS HIGH_LOGISTICS_RATE_FLAG,
    IFF(c.FREIGHT_COST_USD > m.MEDIAN_FREIGHT_COST, TRUE, FALSE) AS HIGH_FREIGHT_COST_FLAG,
    (IFF(c.DELAY_RATE_PCT IS NOT NULL,1,0) + IFF(c.LOGISTICS_COST_RATE_PCT IS NOT NULL,1,0) + IFF(c.FREIGHT_COST_USD IS NOT NULL,1,0)) AS METRIC_COVERAGE_COUNT,
    (IFF(c.DELAY_RATE_PCT > m.MEDIAN_DELAY_RATE,1,0) + IFF(c.LOGISTICS_COST_RATE_PCT > m.MEDIAN_LOGISTICS_RATE,1,0) + IFF(c.FREIGHT_COST_USD > m.MEDIAN_FREIGHT_COST,1,0)) AS RISK_SIGNAL_COUNT,
    CASE
        WHEN (IFF(c.DELAY_RATE_PCT > m.MEDIAN_DELAY_RATE,1,0) + IFF(c.LOGISTICS_COST_RATE_PCT > m.MEDIAN_LOGISTICS_RATE,1,0) + IFF(c.FREIGHT_COST_USD > m.MEDIAN_FREIGHT_COST,1,0)) >= 2 THEN 'HIGH'
        WHEN (IFF(c.DELAY_RATE_PCT > m.MEDIAN_DELAY_RATE,1,0) + IFF(c.LOGISTICS_COST_RATE_PCT > m.MEDIAN_LOGISTICS_RATE,1,0) + IFF(c.FREIGHT_COST_USD > m.MEDIAN_FREIGHT_COST,1,0)) = 1 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_TIER
FROM combined c
CROSS JOIN medians m;
