CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.DATA_QUALITY_SCORECARD AS
SELECT
    'DataCo' AS SOURCE_SYSTEM,
    COUNT(*) AS TOTAL_ROWS,
    SUM(CASE WHEN SALES IS NULL THEN 1 ELSE 0 END) AS NULL_SALES_ROWS,
    ROUND(100.0 * SUM(CASE WHEN SALES IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS NULL_SALES_PCT,
    SUM(CASE WHEN ORDER_DATE IS NULL THEN 1 ELSE 0 END) AS NULL_DATE_ROWS,
    SUM(CASE WHEN DELIVERY_STATUS IS NULL THEN 1 ELSE 0 END) AS NULL_DELIVERY_STATUS_ROWS,
    SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTOMER_ID_ROWS,
    NULL AS NULL_FREIGHT_ROWS,
    NULL AS NULL_FREIGHT_PCT,
    NULL AS NULL_WEIGHT_ROWS,
    NULL AS NULL_WEIGHT_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT
UNION ALL
SELECT
    'SCMS' AS SOURCE_SYSTEM,
    COUNT(*) AS TOTAL_ROWS,
    NULL, NULL,
    SUM(CASE WHEN SCHEDULED_DELIVERY_DATE IS NULL THEN 1 ELSE 0 END),
    NULL,
    NULL,
    SUM(CASE WHEN FREIGHT_COST_IS_NULL THEN 1 ELSE 0 END) AS NULL_FREIGHT_ROWS,
    ROUND(100.0 * SUM(CASE WHEN FREIGHT_COST_IS_NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS NULL_FREIGHT_PCT,
    SUM(CASE WHEN WEIGHT_IS_NULL THEN 1 ELSE 0 END) AS NULL_WEIGHT_ROWS,
    ROUND(100.0 * SUM(CASE WHEN WEIGHT_IS_NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS NULL_WEIGHT_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.SCMS_SHIPMENT_FACT;
