CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.ENTERPRISE_DELIVERY_SCORECARD AS
SELECT
    'ENTERPRISE' AS SCOPE_ID,
    COUNT_IF(DELIVERY_STATUS != 'Shipping canceled') AS NON_CANCELLED_ITEMS,
    COUNT_IF(DELIVERY_STATUS IN ('Advance shipping','Shipping on time')) AS ON_TIME_ITEMS,
    COUNT_IF(DELIVERY_STATUS = 'Late delivery') AS LATE_ITEMS,
    ROUND(100.0 * COUNT_IF(DELIVERY_STATUS IN ('Advance shipping','Shipping on time'))
        / NULLIF(COUNT_IF(DELIVERY_STATUS != 'Shipping canceled'), 0), 6)
        AS ON_TIME_DELIVERY_PCT,
    ROUND(100.0 * COUNT_IF(DELIVERY_STATUS = 'Late delivery')
        / NULLIF(COUNT_IF(DELIVERY_STATUS != 'Shipping canceled'), 0), 6)
        AS DELAY_RATE_PCT,
    ROUND(AVG(CASE WHEN DELIVERY_STATUS != 'Shipping canceled'
                    AND DAYS_FOR_SHIPPING_REAL > DAYS_FOR_SHIPMENT_SCHEDULED
              THEN DAYS_FOR_SHIPPING_REAL - DAYS_FOR_SHIPMENT_SCHEDULED END), 6)
        AS AVG_DELIVERY_DELAY_DAYS,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
    COUNT(*) AS ORDER_ITEM_COUNT,
    ROUND(SUM(SALES), 6) AS TOTAL_SALES,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER), 6) AS TOTAL_PROFIT,
    ROUND(100.0 * SUM(ORDER_PROFIT_PER_ORDER) / NULLIF(SUM(SALES), 0), 6) AS PROFIT_MARGIN_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.ENTERPRISE_LOGISTICS_SCORECARD AS
SELECT
    'ENTERPRISE' AS SCOPE_ID,
    COUNT(*) AS SHIPMENT_COUNT,
    ROUND(SUM(LINE_ITEM_VALUE), 2) AS TOTAL_SHIPMENT_VALUE,
    ROUND(SUM(FREIGHT_COST_USD), 2) AS TOTAL_FREIGHT_COST,
    ROUND(SUM(LINE_ITEM_INSURANCE_USD), 2) AS TOTAL_INSURANCE_COST,
    ROUND(100.0 * SUM(FREIGHT_COST_USD) / NULLIF(SUM(LINE_ITEM_VALUE), 0), 6) AS LOGISTICS_COST_RATE_PCT,
    SUM(CASE WHEN FREIGHT_COST_IS_NULL THEN 1 ELSE 0 END) AS NULL_FREIGHT_ROWS,
    ROUND(100.0 * SUM(CASE WHEN FREIGHT_COST_IS_NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS NULL_FREIGHT_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.SCMS_SHIPMENT_FACT;
