CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.SUPPLIER_SCORECARD AS
SELECT
    VENDOR AS SUPPLIER,
    COUNT(*) AS SHIPMENT_LINE_COUNT,
    COUNT(DISTINCT COUNTRY) AS COUNTRIES_SERVED,
    COUNT(DISTINCT MANUFACTURING_SITE) AS MANUFACTURING_SITES,
    SUM(LINE_ITEM_QUANTITY) AS TOTAL_QUANTITY,
    ROUND(SUM(LINE_ITEM_VALUE), 2) AS SHIPMENT_VALUE_USD,
    ROUND(SUM(FREIGHT_COST_USD), 2) AS FREIGHT_COST_USD,
    ROUND(SUM(LINE_ITEM_INSURANCE_USD), 2) AS INSURANCE_COST_USD,
    ROUND(100.0 * SUM(FREIGHT_COST_USD) / NULLIF(SUM(LINE_ITEM_VALUE), 0), 2) AS LOGISTICS_COST_RATE_PCT,
    ROUND(AVG(WEIGHT_KILOGRAMS), 2) AS AVG_WEIGHT_KG
FROM SUPPLYCHAINIQ_COCO.CORE.SCMS_SHIPMENT_FACT
WHERE VENDOR IS NOT NULL
GROUP BY VENDOR;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.MANUFACTURING_SITE_SCORECARD AS
SELECT
    MANUFACTURING_SITE AS SITE_NAME,
    COUNT(*) AS SHIPMENT_LINE_COUNT,
    COUNT(DISTINCT VENDOR) AS SUPPLIER_COUNT,
    COUNT(DISTINCT COUNTRY) AS COUNTRIES_SERVED,
    SUM(LINE_ITEM_QUANTITY) AS TOTAL_QUANTITY,
    ROUND(SUM(LINE_ITEM_VALUE), 2) AS SHIPMENT_VALUE_USD,
    ROUND(SUM(FREIGHT_COST_USD), 2) AS FREIGHT_COST_USD,
    ROUND(SUM(LINE_ITEM_INSURANCE_USD), 2) AS INSURANCE_COST_USD,
    ROUND(100.0 * SUM(FREIGHT_COST_USD) / NULLIF(SUM(LINE_ITEM_VALUE), 0), 2) AS LOGISTICS_COST_RATE_PCT,
    ROUND(AVG(WEIGHT_KILOGRAMS), 2) AS AVG_WEIGHT_KG
FROM SUPPLYCHAINIQ_COCO.CORE.SCMS_SHIPMENT_FACT
WHERE MANUFACTURING_SITE IS NOT NULL
GROUP BY MANUFACTURING_SITE;
