CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.MONTHLY_DELIVERY_TREND AS
SELECT
    DATE_TRUNC('MONTH', ORDER_DATE)::DATE AS MONTH_START,
    COUNT_IF(DELIVERY_STATUS != 'Shipping canceled') AS NON_CANCELLED_ITEMS,
    COUNT_IF(DELIVERY_STATUS IN ('Advance shipping','Shipping on time')) AS ON_TIME_ITEMS,
    ROUND(100.0 * COUNT_IF(DELIVERY_STATUS IN ('Advance shipping','Shipping on time'))
        / NULLIF(COUNT_IF(DELIVERY_STATUS != 'Shipping canceled'), 0), 2) AS ON_TIME_DELIVERY_PCT,
    ROUND(100.0 * COUNT_IF(DELIVERY_STATUS = 'Late delivery')
        / NULLIF(COUNT_IF(DELIVERY_STATUS != 'Shipping canceled'), 0), 2) AS DELAY_RATE_PCT,
    ROUND(AVG(CASE WHEN DELIVERY_STATUS != 'Shipping canceled'
                    AND DAYS_FOR_SHIPPING_REAL > DAYS_FOR_SHIPMENT_SCHEDULED
              THEN DAYS_FOR_SHIPPING_REAL - DAYS_FOR_SHIPMENT_SCHEDULED END), 2) AS AVG_DELIVERY_DELAY_DAYS,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER), 2) AS TOTAL_PROFIT,
    ROUND(100.0 * SUM(ORDER_PROFIT_PER_ORDER) / NULLIF(SUM(SALES), 0), 2) AS PROFIT_MARGIN_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT
GROUP BY DATE_TRUNC('MONTH', ORDER_DATE)
ORDER BY MONTH_START;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.SEMANTIC.MONTHLY_LOGISTICS_TREND AS
SELECT
    DATE_TRUNC('MONTH', SCHEDULED_DELIVERY_DATE)::DATE AS MONTH_START,
    COUNT(*) AS SHIPMENT_COUNT,
    ROUND(SUM(LINE_ITEM_VALUE), 2) AS SHIPMENT_VALUE_USD,
    ROUND(SUM(FREIGHT_COST_USD), 2) AS FREIGHT_COST_USD,
    ROUND(100.0 * SUM(FREIGHT_COST_USD) / NULLIF(SUM(LINE_ITEM_VALUE), 0), 2) AS LOGISTICS_COST_RATE_PCT
FROM SUPPLYCHAINIQ_COCO.CORE.SCMS_SHIPMENT_FACT
GROUP BY DATE_TRUNC('MONTH', SCHEDULED_DELIVERY_DATE)
ORDER BY MONTH_START;
