CREATE OR REPLACE TABLE SUPPLYCHAINIQ_COCO.CORE.CUSTOMER_DIM AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CUSTOMER_ID)     AS CUSTOMER_SK,
    CUSTOMER_ID,
    CUSTOMER_FNAME,
    CUSTOMER_LNAME,
    CUSTOMER_SEGMENT,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_COUNTRY,
    CUSTOMER_ZIPCODE,
    CUSTOMER_STREET,
    CUSTOMER_EMAIL
FROM (
    SELECT DISTINCT
        CUSTOMER_ID,
        CUSTOMER_FNAME,
        CUSTOMER_LNAME,
        CUSTOMER_SEGMENT,
        CUSTOMER_CITY,
        CUSTOMER_STATE,
        CUSTOMER_COUNTRY,
        CUSTOMER_ZIPCODE,
        CUSTOMER_STREET,
        CUSTOMER_EMAIL
    FROM SUPPLYCHAINIQ_COCO.RAW.RAW_DATACO
    WHERE CUSTOMER_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE DESC) = 1
);
