CREATE OR REPLACE TABLE SUPPLYCHAINIQ_COCO.CORE.GEOGRAPHY_DIM AS
WITH dataco_countries AS (
    SELECT DISTINCT cm.CANONICAL_COUNTRY_NAME AS COUNTRY_NAME
    FROM SUPPLYCHAINIQ_COCO.RAW.RAW_DATACO r
    JOIN SUPPLYCHAINIQ_COCO.CORE.COUNTRY_MAPPING cm
        ON r.ORDER_COUNTRY = cm.SOURCE_COUNTRY_NAME AND cm.SOURCE_SYSTEM = 'DATACO'
    WHERE r.ORDER_COUNTRY IS NOT NULL
),
scms_countries AS (
    SELECT DISTINCT cm.CANONICAL_COUNTRY_NAME AS COUNTRY_NAME
    FROM SUPPLYCHAINIQ_COCO.RAW.RAW_SCMS r
    JOIN SUPPLYCHAINIQ_COCO.CORE.COUNTRY_MAPPING cm
        ON r.COUNTRY = cm.SOURCE_COUNTRY_NAME AND cm.SOURCE_SYSTEM = 'SCMS'
    WHERE r.COUNTRY IS NOT NULL
),
all_countries AS (
    SELECT COUNTRY_NAME FROM dataco_countries
    UNION
    SELECT COUNTRY_NAME FROM scms_countries
)
SELECT
    a.COUNTRY_NAME,
    EXISTS(SELECT 1 FROM dataco_countries d WHERE d.COUNTRY_NAME = a.COUNTRY_NAME) AS IN_DATACO,
    EXISTS(SELECT 1 FROM scms_countries s WHERE s.COUNTRY_NAME = a.COUNTRY_NAME)   AS IN_SCMS,
    CASE
        WHEN EXISTS(SELECT 1 FROM dataco_countries d WHERE d.COUNTRY_NAME = a.COUNTRY_NAME)
         AND EXISTS(SELECT 1 FROM scms_countries s WHERE s.COUNTRY_NAME = a.COUNTRY_NAME)
        THEN 'BOTH'
        WHEN EXISTS(SELECT 1 FROM dataco_countries d WHERE d.COUNTRY_NAME = a.COUNTRY_NAME)
        THEN 'DATACO_ONLY'
        ELSE 'SCMS_ONLY'
    END AS SOURCE_COVERAGE
FROM all_countries a;
