CREATE OR REPLACE TABLE SUPPLYCHAINIQ_COCO.CORE.MANUFACTURING_SITE_DIM AS
SELECT
    ROW_NUMBER() OVER (ORDER BY MANUFACTURING_SITE) AS SITE_SK,
    MANUFACTURING_SITE                              AS SITE_NAME
FROM (
    SELECT DISTINCT MANUFACTURING_SITE
    FROM SUPPLYCHAINIQ_COCO.RAW.RAW_SCMS
    WHERE MANUFACTURING_SITE IS NOT NULL
);
