CREATE OR REPLACE TABLE SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT AS
SELECT
    r.ORDER_ITEM_ID,
    r.ORDER_ID,
    r.CUSTOMER_ID,
    r.PRODUCT_CARD_ID,
    r.ORDER_DATE,
    r.SHIPPING_DATE,
    r.ORDER_TYPE,
    r.DELIVERY_STATUS,
    r.LATE_DELIVERY_RISK,
    r.ORDER_ITEM_QUANTITY,
    r.SALES,
    r.ORDER_ITEM_PRODUCT_PRICE,
    r.ORDER_ITEM_DISCOUNT,
    r.ORDER_ITEM_DISCOUNT_RATE,
    r.ORDER_ITEM_TOTAL,
    r.ORDER_PROFIT_PER_ORDER,
    r.ORDER_ITEM_PROFIT_RATIO,
    r.DAYS_FOR_SHIPPING_REAL,
    r.DAYS_FOR_SHIPMENT_SCHEDULED,
    r.SHIPPING_MODE,
    r.ORDER_STATUS,
    r.ORDER_COUNTRY,
    COALESCE(cm.CANONICAL_COUNTRY_NAME, r.ORDER_COUNTRY) AS CANONICAL_COUNTRY,
    r.ORDER_REGION,
    r.ORDER_STATE,
    r.ORDER_CITY,
    r.MARKET,
    r.CATEGORY_NAME,
    r.DEPARTMENT_NAME,
    r.PRODUCT_NAME
FROM SUPPLYCHAINIQ_COCO.RAW.RAW_DATACO r
LEFT JOIN SUPPLYCHAINIQ_COCO.CORE.COUNTRY_MAPPING cm
    ON r.ORDER_COUNTRY = cm.SOURCE_COUNTRY_NAME
    AND cm.SOURCE_SYSTEM = 'DATACO';
