CREATE OR REPLACE TABLE SUPPLYCHAINIQ_COCO.CORE.PRODUCT_DIM AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PRODUCT_CARD_ID) AS PRODUCT_SK,
    PRODUCT_CARD_ID,
    PRODUCT_CATEGORY_ID,
    PRODUCT_NAME,
    PRODUCT_PRICE,
    PRODUCT_STATUS,
    CATEGORY_ID,
    CATEGORY_NAME,
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    PRODUCT_DESCRIPTION,
    PRODUCT_IMAGE
FROM (
    SELECT DISTINCT
        PRODUCT_CARD_ID,
        PRODUCT_CATEGORY_ID,
        PRODUCT_NAME,
        PRODUCT_PRICE,
        PRODUCT_STATUS,
        CATEGORY_ID,
        CATEGORY_NAME,
        DEPARTMENT_ID,
        DEPARTMENT_NAME,
        PRODUCT_DESCRIPTION,
        PRODUCT_IMAGE
    FROM SUPPLYCHAINIQ_COCO.RAW.RAW_DATACO
    WHERE PRODUCT_CARD_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY PRODUCT_CARD_ID ORDER BY ORDER_DATE DESC) = 1
);
