CREATE OR REPLACE TABLE SUPPLYCHAINIQ_COCO.CORE.SUPPLIER_DIM AS
SELECT
    ROW_NUMBER() OVER (ORDER BY VENDOR) AS SUPPLIER_SK,
    VENDOR                              AS VENDOR_NAME
FROM (
    SELECT DISTINCT VENDOR
    FROM SUPPLYCHAINIQ_COCO.RAW.RAW_SCMS
    WHERE VENDOR IS NOT NULL
);
