CREATE OR REPLACE TABLE SUPPLYCHAINIQ_COCO.RAW.RAW_SCMS AS
SELECT
    TRY_CAST(ID AS NUMBER)                                       AS SHIPMENT_ID,
    TRIM(PROJECT_CODE)                                           AS PROJECT_CODE,
    TRIM(PQ_NUMBER)                                              AS PQ_NUMBER,
    TRIM(PO_SO_NUMBER)                                           AS PO_SO_NUMBER,
    TRIM(ASN_DN_NUMBER)                                          AS ASN_DN_NUMBER,
    TRIM(COUNTRY)                                                AS COUNTRY,
    TRIM(MANAGED_BY)                                             AS MANAGED_BY,
    TRIM(FULFILL_VIA)                                            AS FULFILL_VIA,
    TRIM(VENDOR_INCO_TERM)                                       AS VENDOR_INCO_TERM,
    TRIM(SHIPMENT_MODE)                                          AS SHIPMENT_MODE,
    TRY_TO_DATE(PQ_FIRST_SENT_TO_CLIENT_DATE, 'DD-MON-YY')      AS PQ_FIRST_SENT_TO_CLIENT_DATE,
    TRY_TO_DATE(PO_SENT_TO_VENDOR_DATE, 'DD-MON-YY')            AS PO_SENT_TO_VENDOR_DATE,
    TRY_TO_DATE(SCHEDULED_DELIVERY_DATE, 'DD-MON-YY')           AS SCHEDULED_DELIVERY_DATE,
    TRY_TO_DATE(DELIVERED_TO_CLIENT_DATE, 'DD-MON-YY')          AS DELIVERED_TO_CLIENT_DATE,
    TRY_TO_DATE(DELIVERY_RECORDED_DATE, 'DD-MON-YY')            AS DELIVERY_RECORDED_DATE,
    TRIM(PRODUCT_GROUP)                                          AS PRODUCT_GROUP,
    TRIM(SUB_CLASSIFICATION)                                     AS SUB_CLASSIFICATION,
    TRIM(VENDOR)                                                 AS VENDOR,
    TRIM(ITEM_DESCRIPTION)                                       AS ITEM_DESCRIPTION,
    TRIM(MOLECULE_TEST_TYPE)                                     AS MOLECULE_TEST_TYPE,
    TRIM(BRAND)                                                  AS BRAND,
    TRIM(DOSAGE)                                                 AS DOSAGE,
    TRIM(DOSAGE_FORM)                                            AS DOSAGE_FORM,
    TRIM(UNIT_OF_MEASURE_PER_PACK)                               AS UNIT_OF_MEASURE_PER_PACK,
    TRY_CAST(LINE_ITEM_QUANTITY AS NUMBER)                       AS LINE_ITEM_QUANTITY,
    TRY_CAST(LINE_ITEM_VALUE AS FLOAT)                           AS LINE_ITEM_VALUE,
    TRY_CAST(PACK_PRICE AS FLOAT)                                AS PACK_PRICE,
    TRY_CAST(UNIT_PRICE AS FLOAT)                                AS UNIT_PRICE,
    TRIM(MANUFACTURING_SITE)                                     AS MANUFACTURING_SITE,
    TRIM(FIRST_LINE_DESIGNATION)                                 AS FIRST_LINE_DESIGNATION,
    TRY_CAST(WEIGHT_KILOGRAMS AS FLOAT)                          AS WEIGHT_KILOGRAMS,
    TRY_CAST(FREIGHT_COST_USD AS FLOAT)                          AS FREIGHT_COST_USD,
    TRY_CAST(LINE_ITEM_INSURANCE_USD AS FLOAT)                   AS LINE_ITEM_INSURANCE_USD
FROM SUPPLYCHAINIQ.RAW.RAW_SCMS;
