-- Entity views: thin projections of CORE tables for ontology consumers
-- Each view represents a single business entity at its natural grain.

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ONTOLOGY.CUSTOMER AS
SELECT CUSTOMER_ID, CUSTOMER_FNAME, CUSTOMER_LNAME, CUSTOMER_SEGMENT,
       CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_COUNTRY, CUSTOMER_ZIPCODE
FROM SUPPLYCHAINIQ_COCO.CORE.CUSTOMER_DIM;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ONTOLOGY.PRODUCT AS
SELECT PRODUCT_CARD_ID, PRODUCT_CATEGORY_ID, PRODUCT_NAME, PRODUCT_PRICE,
       PRODUCT_STATUS, CATEGORY_ID, CATEGORY_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
FROM SUPPLYCHAINIQ_COCO.CORE.PRODUCT_DIM;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ONTOLOGY.ORDERS AS
SELECT ORDER_ID, CUSTOMER_ID, MIN(ORDER_DATE) AS ORDER_DATE,
       ORDER_COUNTRY, CANONICAL_COUNTRY, ORDER_REGION, ORDER_STATE, ORDER_CITY,
       ORDER_STATUS, MARKET
FROM SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT
GROUP BY ORDER_ID, CUSTOMER_ID, ORDER_COUNTRY, CANONICAL_COUNTRY, ORDER_REGION, ORDER_STATE,
         ORDER_CITY, ORDER_STATUS, MARKET;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ONTOLOGY.ORDER_ITEM AS
SELECT ORDER_ITEM_ID, ORDER_ID, CUSTOMER_ID, PRODUCT_CARD_ID,
       ORDER_DATE, DELIVERY_STATUS, ORDER_ITEM_QUANTITY, SALES,
       ORDER_PROFIT_PER_ORDER, DAYS_FOR_SHIPPING_REAL,
       DAYS_FOR_SHIPMENT_SCHEDULED, SHIPPING_DATE, SHIPPING_MODE
FROM SUPPLYCHAINIQ_COCO.CORE.ORDER_ITEM_FACT;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ONTOLOGY.SUPPLIER AS
SELECT SUPPLIER_SK, VENDOR_NAME
FROM SUPPLYCHAINIQ_COCO.CORE.SUPPLIER_DIM;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ONTOLOGY.MANUFACTURING_SITE AS
SELECT SITE_SK, SITE_NAME
FROM SUPPLYCHAINIQ_COCO.CORE.MANUFACTURING_SITE_DIM;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ONTOLOGY.SHIPMENT AS
SELECT SHIPMENT_ID, PROJECT_CODE, PQ_NUMBER, PO_SO_NUMBER, ASN_DN_NUMBER,
       COUNTRY, VENDOR, MANUFACTURING_SITE, SHIPMENT_MODE,
       SCHEDULED_DELIVERY_DATE, DELIVERED_TO_CLIENT_DATE,
       LINE_ITEM_QUANTITY, LINE_ITEM_VALUE, FREIGHT_COST_USD,
       LINE_ITEM_INSURANCE_USD, WEIGHT_KILOGRAMS,
       PRODUCT_GROUP, BRAND, DOSAGE_FORM
FROM SUPPLYCHAINIQ_COCO.CORE.SCMS_SHIPMENT_FACT;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ONTOLOGY.LOGISTICS AS
SELECT SHIPMENT_ID, VENDOR AS SUPPLIER_NAME, COUNTRY, SHIPMENT_MODE,
       LINE_ITEM_VALUE, FREIGHT_COST_USD, LINE_ITEM_INSURANCE_USD,
       WEIGHT_KILOGRAMS, FREIGHT_COST_IS_NULL, WEIGHT_IS_NULL
FROM SUPPLYCHAINIQ_COCO.CORE.SCMS_SHIPMENT_FACT;

CREATE OR REPLACE VIEW SUPPLYCHAINIQ_COCO.ONTOLOGY.GEOGRAPHY AS
SELECT COUNTRY_NAME, IN_DATACO, IN_SCMS, SOURCE_COVERAGE
FROM SUPPLYCHAINIQ_COCO.CORE.GEOGRAPHY_DIM;
